### ISSUE TITLE
Web site says Twiggy almost Python 3 compatible, but it is

### ISSUE THREAD

**Issue by msabramo** [caniusepython3/caniusepython3.com#40]
https://pypi.python.org/pypi/Twiggy

has the Python 3 classifier

and the `caniusepython3` CLI tool says that it's Python 3 compatible:

```
$ caniusepython3 --projects Twiggy
Finding and checking dependencies ...
[WARNING] Stale overrides: set([u'python-neutronclient'])

You have 0 projects blocking you from using Python 3!
```

but https://caniusepython3.com/project/Twiggy says that there's 1 blocker, although I can't tell what it is:

![screen shot 2015-03-10 at 11 07 00 am](https://cloud.githubusercontent.com/assets/305268/6581935/4795e776-c717-11e4-85f3-02d17d342584.png)

Maybe a cache needs to be cleared? Twiggy only gained the Python 3 classifier yesterday, so I'm wondering if caching is the cause and it might even sort itself out in a day or two.

**Comment by msabramo** [comment]
Twiggy still showing up as not Python 3 compatible. I don't know why.

**Comment by svisser** [comment]
This issue also occurs with `pidfile`:

- https://caniusepython3.com/project/pidfile says it's not compatible.
- `caniusepython3 -p pidfile` says it is compatible (which matches the information on PyPI).

**Comment by palfrey** [comment]
These now appear fixed

**Comment by msabramo** [comment]
Yep these seem to be fixed. Not sure why, but it's working now.
