### ISSUE TITLE
TLS certificate has expired

### ISSUE THREAD

**Issue by chhantyal** [caniusepython3/caniusepython3.com#51]
https://caniusepython3.com/

**Comment by philfreo** [comment]
@tricoder42 Are you planning on fixing this?

**Comment by tricoder42** [comment]
It's fixed now, deployed cert from https://letsencrypt.org

Sorry for the inconvenience!

**Comment by TiernanKennedy** [comment]
@tricoder42 it's not working again, was planning to move to Python 3 but have given up now!! 😉

**Comment by tricoder42** [comment]
@TiernanKennedy Fixed! The path to Python 3 is clear again :)

**Comment by TiernanKennedy** [comment]
Haha fantastic nice work @tricoder42
