### ISSUE TITLE
Fix uptime check

### ISSUE THREAD

**Issue by rolando** [caniusepython3/caniusepython3.com#54]
Site https://caniusepython3.com/ returns `502 Bad Gateway` at this time.

**Comment by tricoder42** [comment]
Fixed! Sorry for this happened

**Comment by tricoder42** [comment]
I'll fix uptime check and figure out what caused the problem, so we can prevent it in the future

**Comment by rolando** [comment]
@tricoder42 thank you for such great library!

**Comment by tricoder42** [comment]
I'm not author of the library and I'm not even the original author of this app. I'm just a maintainer ;)

**Comment by tricoder42** [comment]
Alright, uptime check is running
