### ISSUE TITLE
SSL certificate of https://caniusepython3.com is expired

### ISSUE THREAD

**Issue by TimDumol** [caniusepython3/caniusepython3.com#55]
Hi there,

Just in case you haven't noticed: your Let's Encrypt certificate for https://caniusepython3.com has expired. Thanks for providing this great service!

**Comment by tricoder42** [comment]
Hi! Sorry, I've been on vacation and forgot to check certificates before I left... I've just deployed renewed cert.

Thank you for report! 😃

**Comment by TimDumol** [comment]
No problem! Thanks for your swift response, and for making this project in the first place :grinning:

**Comment by tricoder42** [comment]
All kudos goes to @jezdez, I'm just a maintainer ;)

**Comment by jezdez** [comment]
The project wouldn't exist anymore if not for a maintainer, so all the thanks to @tricoder42! 🎁
