### ISSUE TITLE
HTTPS certificate expired

### ISSUE THREAD

**Issue by sheljohn** [caniusepython3/caniusepython3.com#60]
Currently, trying to connect to `https://caniusepython3.com` leads to a security notice saying that the SSL certificate expired 18 days ago.

FYI trying to connect to `http://caniusepython3.com` instead (ie not secure), leads to an Nginx thank-you page.

**Comment by tricoder42** [comment]
Fixed and set certbot to auto renew certificate.

Thank you for reporting!
