### ISSUE TITLE
HTTPS redirect broken in chrome (ERR_INVALID_REDIRECT)

### ISSUE THREAD

**Issue by gricey432** [caniusepython3/caniusepython3.com#61]
If I click the link on Github to visit the site, Chrome (64.0.3282.186 Linux) shows an invalid redirect error.

If I manually enter "https://" at the start of the url it works fine.

![caniuse](https://user-images.githubusercontent.com/1611345/38719043-509db69a-3f33-11e8-8ba4-244b2cffad91.png)

**Comment by tricoder42** [comment]
Hi @gricey432, thanks!
The url in repo description seems to be correct. I found there was missing `https` in README, so I [fixed](https://github.com/caniusepython3/caniusepython3.com/commit/4c46b4d0198af25aa4dd2a3b9cdb4b4147242b6b) that. Please let me know if the problem persists! Cheers 👍
