### ISSUE TITLE
Security certificate expired

### ISSUE THREAD

**Issue by Eric-Arellano** [caniusepython3/caniusepython3.com#62]
Hello, I'm running into this warning from Chrome when I try to visit the site.

![screen shot 2018-06-29 at 4 45 51 pm](https://user-images.githubusercontent.com/14852634/42114149-f72cfa06-7bbb-11e8-9049-49278f663d03.png)

Think the security certificate needs to be updated.

Thanks!

**Comment by tricoder42** [comment]
Thanks, it's fixed now. I have to investigate, why nginx doesn't reload certs after certbot renews them...

**Comment by tricoder42** [comment]
Oh, I see! Certbot package installs it's own crontab entry, but without `--deploy-hook` (https://www.guyrutenberg.com/2017/01/01/lets-encrypt-reload-nginx-after-renewing-certificates/, although the article uses --renew-hook instead of --deploy-hook). Solved for the future renewals as well!

**Comment by Eric-Arellano** [comment]
Thanks for fixing this so quickly!
