### ISSUE TITLE
Expired TLS certificate on caniusepython3.com

### ISSUE THREAD

**Issue by mbi** [caniusepython3/caniusepython3.com#63]
The cert for https://caniusepython3.com/ expired on 28 August 2018, 13:03:27 GMT+2. The current time is August 29, 2018, 2:06 PM.

Likely the same issue as #62?

**Comment by tricoder42** [comment]
Hey @mbi,
this is really annoying, for some reason certbot doesn't trigger deploy hook.

It's fixed now, thank you for reporting!

**Comment by mbi** [comment]
Thank you for your quick reaction!

(I usually just reload nginx regardless of whether there was a renew or not, i.e. `certbot renew -q && service nginx restart` in `cron.daily`. Crude but effective.)
