### ISSUE TITLE
Expired TLS certificate on caniusepython3.com

### ISSUE THREAD

**Issue by erikagnvall** [caniusepython3/caniusepython3.com#64]
Looks like this was reported before (#63, #62) but now the website uses HSTS so Firefox won't even allow me to add a temporary exception:

![screen shot 2018-10-29 at 12 43 28](https://user-images.githubusercontent.com/80468/47647837-82187700-db78-11e8-9c1a-7ee77d6485e8.png)

**Comment by tricoder42** [comment]
Hey @Meldanya, sorry, this is really annoying. For some reason `--deploy-hook` doesn't run after cert renewal.

Server upgraded, rebooted, crontab slightly modified (I'm using `systemctl reload nginx` instead of `nginx -s reload`) and we'll see how it goes.

This is the full crontab line:

```
@monthly certbot renew --deploy-hook "systemctl reload nginx"
```

Cheers

**Comment by erikagnvall** [comment]
No problems, I worked around it by installing and running `caniusepython3` locally :)

Regarding certbot config, we're running with the [nginx](https://certbot.eff.org/docs/using.html#nginx) plugin which seems to be working fine. Renewing and reloading nginx hasn't hit a snag since the server was installed around a year ago. Not sure how your setup looks but it might be an alternative if it keeps happening?
