### ISSUE TITLE
Redirect Issue 

### ISSUE THREAD

**Issue by fahadmehar** [caniusepython3/caniusepython3.com#65]
I have (ERR_INVALID_REDIRECT) in all browsers ? How I fix this ? when I I manually enter "https://" it works.

**Comment by tricoder42** [comment]
Ah, my bad. Wrong nginx config :lame:

It should be fixed now (clear the cache to test it).

**Comment by fahadmehar** [comment]
I didn't get what you said"?

**Comment by tricoder42** [comment]
The nginx configuration was wrong. I fixed it, test it in browser after cleaning the cache and it worked. I assume it should be fixed now.
