### ISSUE TITLE
may I comaintain?

### ISSUE THREAD

**Issue by brainwane** [caniusepython3/caniusepython3.com#66]
Hi @tricoder42 & @jezdez! Thank you for maintaining caniusepython3.com.

I'd love to be able to point to the site as part of [the work I'm doing spreading the word about the EOL for Python 2.x](https://www.harihareswara.net/sumana/2019/08/05/0) -- along the way it would be good to fix a few bugs in this site. Would you be interested in me co-maintaining it for the next few months?

Thanks!

cc @brettcannon in case you want to weigh in.

**Comment by jezdez** [comment]
Hello! I've handed this over to @tricoder42 so I'm not in the position to answer this. I've been wondering for a while though if this would be a good site to move to the PSF's hosting to reduce cost and improve maintenance?

**Comment by brainwane** [comment]
Thanks @jezdez - I've asked [on the PSF infrastructure mailing list](https://mail.python.org/mailman/listinfo/infrastructure).

**Comment by brettcannon** [comment]
Since I have nothing to do with the site I have absolute no objections to more maintainers for it. 😉 

And just an FYI, I plan to continue to keep the exceptions file updated for caniusepython3 until at least until PyCon US 2020, but past that I haven't made a decision yet. I also don't really plan on any new features for it.

**Comment by jezdez** [comment]
> Since I have nothing to do with the site I have absolute no objections to more maintainers for it. 😉

Apologies for earlier not mentioning you in the list of people, I blindly assumed that you're okay with that, thank you for noticing it and speaking up.

> And just an FYI, I plan to continue to keep the exceptions file updated for caniusepython3 until at least until PyCon US 2020, but past that I haven't made a decision yet. I also don't really plan on any new features for it.

Interesting! Maybe that would be a good chance to move the core functionality of the CLI tool into the site's code (including the list of exceptions) and maintain it via the regular pull request maintenance mode?

The advantage would be a reduced maintenance effort by using continuous develivery of the website code and no more package releases. The CLI tool could start displaying deprecation warnings in 2020 and point to the website instead.

**Comment by ewdurbin** [comment]
If moving the hosting for this site into the PSF infrastructure is desired, that's supportable.

I'm not sure what more the PSF can directly offer at this point than taking over the cost and management of:
  - Domain Registration
  - DNS
  - Hosting (looks like Heroku would be a perfect fit?)

**Comment by brainwane** [comment]
I pinged @tricoder42 via email to ask them to look at this issue.

**Comment by brainwane** [comment]
@tricoder42 gave me committer access to this repository. Thank you!

@ewdurbin I see that @jezdez +1'd your last comment, so, sounds like we should start the process of moving it into/onto PSF's hosting. Closing this issue - we can followup in https://github.com/python/psf-infra-meta/issues/38 .
